### ISSUE TITLE
PG0 - Content Type - Body text wrapping

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#10]
Text Wrapping for one long string of "characters" (aaaaaa...) goes off the page and shows a horizontal scroll bar to follow the text.

**Comment by brharp** [comment]
What *would* be the expected behaviour in this scenario? Are you expecting the word to be hyphenated automatically?

**Comment by mmafe** [comment]
We could either:
a) Leave it and expect people to post content mindfully so it does not go off the page. Only issue is when we get down to the narrow view of the page, authors will have less characters at their disposal.

b) Maybe do a word-wrap? https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

Joe, since it's labelled P0, is this solely a back-end thing or is it affected specific views on the front-end?

**Comment by jszasz** [comment]
Well there is only one view type for a Basic Page (P1), but i assumed that somewhere in the editor for a Basic Page (P0) we would probably want to add the word-wrap:

<code> word-wrap: break-word; </code>

The examples on that page you linked is exactly what is happening. It does only appear on the view (P1) though, so maybe we should change the issue to that view.

**Comment by JProxxi** [comment]
This issue is still present.

**Comment by nevantan** [comment]
Issue seems to have been resolved.
![iss10](https://cloud.githubusercontent.com/assets/25013998/21938869/30ec9e1a-d98b-11e6-8c0e-67b0a596038c.png)
