### ISSUE TITLE
G0 - Editor settings - Wysiwyg (Full HTML)

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#16]
wbsadmin has access to Basic HTML, Full HTML, and Plain text for text formats when typing in a body.
Authors have access to Basic HTML and Pain text.

Check settings for who is allowed which editor settings

**Comment by brharp** [comment]
Author, editor, moderator, publisher all have access to all text formats.

**Comment by mmafe** [comment]
We are revisiting this issue now that site manager exists. Discuss access permissions for Full html, security ramifications, and potential for giving full html access only to site manager.

**Comment by brharp** [comment]
In order to make this change happen we need tests in ug_wysiwyg that demonstrate:

- *all* markup generated by the Filtered HTML toolbar is allowed
- *only* markup generated by the Filtered HTML toolbar is allowed
- *all* Bootstrap classes are allowed
- *only* Bootstrap classes are allowed

The tests should not be complicated to write: generate a node with the filtered_html text format, generate some markup, and assert that the appropriate markup is allowed or filtered out. The [xpath](https://api.drupal.org/api/drupal/modules!simpletest!drupal_web_test_case.php/function/DrupalWebTestCase%3A%3Axpath/7.x)() method of DrupalWebTestCase may be useful here.

**Comment by JProxxi** [comment]
Issue remains open, tests still need to be developed. See brharps comment above.

**Comment by mmafe** [comment]
**Github Triage Meeting Notes:** Issue is not necessarily about removing full_html. It is more about refining filtered_html.

**Comment by mmafe** [comment]
@tqureshi-uog mentioned the following module as a possible solution for being able to use specific grid templates in filtered html: https://www.drupal.org/project/wysiwyg_template

**Comment by mmafe** [comment]
Added to Kanban board

**Comment by brharp** [comment]
Review `modules/filter/filter.test', particularly its use of `assertFilteredString' for examples of how to effeciently test a wide variety of input strings. The tests should demonstrate that markup generated by CKEditor (using the Bootstrap classes) is allowed, and everything else is stripped out.

**Comment by mmafe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unit Test - Issue 16](https://trello.com/c/3FdmOTMh/1893-unit-test-issue-16)

**Comment by mmafe** [comment]
@brharp Has a list of approved markup for Filtered HTML and Full HTML been decided on? 

For example, I noticed that <font> is an obsolete tag that causes validation issues, but it's currently allowed in Filtered HTML. Can I add that to the list of things to be stripped out by Filtered HTML?

**Comment by brharp** [comment]
I believe the criteria are:

·         all markup generated by the Filtered HTML toolbar is allowed

·         only markup generated by the Filtered HTML toolbar is allowed

·         all Bootstrap classes are allowed

·         only Bootstrap classes are allowed
By these criteria, <font> would not be allowed.
