### ISSUE TITLE
G4 - Local navigation submenus on the far right get visually cut off (wide view)

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#168]
Local navigation submenus on the far right get visually cut off

![window-cutoff](https://cloud.githubusercontent.com/assets/1927902/9390888/ea43a7c4-4741-11e5-95f2-5d3dada9cfd2.jpg)

**Comment by enichol** [comment]
Original issue is fixed, however there is an unintended consequence when the menu items on a page wrap:

![menuclipping](https://cloud.githubusercontent.com/assets/14219820/11567740/73d77e5e-99b6-11e5-9c09-b630ac3bce9b.png)

**Comment by enichol** [comment]
Issue is fixed as much as it can be at this time. Currently the second last menu will go off the right of the page in some cases: 
![menuclipping](https://cloud.githubusercontent.com/assets/14219820/11568860/94ddcb0c-99bc-11e5-9099-4c0f2264da21.png)

However, this is the lesser of all evils, since every other solution introduced a new problem as well.

**Comment by enichol** [comment]
Issue is fixed as much as it can be at this time. Currently the second last menu will go off the right of the page in some cases: 
![menuclipping](https://cloud.githubusercontent.com/assets/14219820/11568860/94ddcb0c-99bc-11e5-9099-4c0f2264da21.png)

However, this is the lesser of all evils, since every other solution introduced a new problem as well.
