### ISSUE TITLE
G3 - Local search has no associated heading

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#204]
I noticed that for every local search input box that isn't on the main page, there is no heading associated with it. There appears to be an invisible h2 that has been commented out:

```
<!-- <h2 class="element-invisible"></h2> -->
```

Not sure if this was intentional or not. While not necessarily an accessibility issue, this is definitely a usability issue since both sighted and screen reader users have no indication that the input box is a local website search.

**Comment by mmafe** [comment]
This issue is related to https://github.com/brharp/hjckrrh/issues/212

We chose to remove the "Search" (screen-reader-only) heading that accompanied the search field. It was causing issues in Siteimprove because the first heading on the page was not a heading 1. We also noticed that neither WebAIM or SimplyAccessible.com are using the headings, so for now, we've commented it out.

Once issue #212 is resolved, users will have a better indication that the input box is a local website search. (Right now, it's only the placeholder text which is not enough.)

**Comment by mmafe** [comment]
**Note:** I'm leaving this open until https://github.com/brharp/hjckrrh/issues/212 and https://github.com/brharp/hjckrrh/issues/170 have been resolved.

**Comment by ushenoyuog** [comment]
Closing this issue as both #212  AND #170 ARE SOLVED.

![image](https://cloud.githubusercontent.com/assets/23462414/25489794/f7687d4e-2b38-11e7-9ca7-7ce20b00ec13.png)
