### ISSUE TITLE
R1- Role ids are a problem

### ISSUE THREAD

**Issue by anncesar** [ccswbs/hjckrrh#269]

**Comment by brharp** [comment]
On second review, the problem is with IMCE. IMCE store its configuration in variables. It stores the assignment of IMCE profiles to different roles, using the profile id and role id. If the ids don't in the feature don't match the ids on the live site, the feature shows as overridden. There is no fix for this issue. There is no newer version of IMCE that may correct the problem. New sites are unlikely to see the ug_wysiwyg feature as overridden, because when the roles are created in a predictable order, the role ids are consistent across sites (2, 3, 4, 5, ...).

If this issue prevents us from pushing important wysiwyg feature changes in the future, the IMCE components could be move into a separate feature.
