### ISSUE TITLE
E0 - Location Field is set as a Rich Text Editor with no set character limit.

### ISSUE THREAD

**Issue by mancusop** [ccswbs/hjckrrh#284]
- Location field has not been defined in Generic Field Descriptions in Dev Documentation
- It has been implemented as a Rich Text Editor field
- This doesn't look like good policy from an Accessibility, security, and efficiency standpoint.

**Accessibility Issue**
- If location is a hoax and set to too many lines screen readers and devices with small screen spaces will have a difficult time displaying the data.

**Security**
- Limiting the amount of times content editors can input full/filtered HTML will limit the amount of avenues that malicious and faulty code injections can occur.

**Efficieny**
- The longest place name in the world is _Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu_ at 85 chars.
- still don't need full body text editing for that.

**Suggestion**
- Set it to a Plain text multi-line field**BOX** with 255 chara max. A fieldbox such that an address can be inputed in the traditional multi-line manner.
- Or change the location element to have multiple input fields like **Building**, **Address**, **Country** etc.

**Comment by mmafe** [comment]
By having it as a rich text field with no set character limit, I believe the intent was to allow content editors to put as much or as little information as they want (eg. directions, detailed location information). Regarding security/the potential for malicious content, the points listed above relate to all situations where editors are inputting content. Since this issue was created, more has been done (see https://github.com/ccswbs/hjckrrh/issues/174) to filter out problematic elements (eg. scripts) and improve accessibility.
