### ISSUE TITLE
FT1 - Break delimiter breaks Title

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#3]
If you use the  delimiter in the Title attribute of a feature, it breaks the content to another line but the '' text is still visible in the title to anyone viewing the featured image

![ft1_lengthbug2](https://cloud.githubusercontent.com/assets/1927902/7639783/88462278-fa4c-11e4-91c8-5e87c1b8f9e3.png)

**Comment by jpinsent** [comment]
Not sure if this issue is relevant anymore. Upon further testing, if you insert the  delimiter into the HTML, it adds an hr break that is visible in the CKEditor, but does not appear to have any effect on the actual feature. 

The only reason this is a problem is because when you click 'Preview' whilst editing a feature, a text box prompts you to use the break delimiter to trim your post:
"The trimmed version of your post shows what your post looks like when promoted to the main page or when exported for syndication. You can insert the delimiter "" (without the quotes) to fine-tune where your post gets split."
