### ISSUE TITLE
Migrate D6 - "System" menus not displaying in Secondary Links

### ISSUE THREAD

**Issue by mmatthews** [ccswbs/hjckrrh#346]
Menus migrated from some D6 site are losing navigation items that are listed as "system" in the database. This could be related to #343. Sites affected are
- https://aoda.web.uoguelph.ca/history/
- https://aoda.web.uoguelph.ca/sets/
- https://aoda.web.uoguelph.ca/sofam/

**Comment by mmafe** [comment]
**Update:** Figured it out!

We are not losing the navigation items. They are being brought over in the database, BUT we need to ensure that the view or page that the system item is pointing to exists on the destination site.

For example, Faculty and Staff on history is pointing to a view that connects to the relative url /faculty-and-staff. When that menu item is brought over, it exists in the database, but Drupal does not recognize it because we don't have a corresponding system-defined page or view that connects up with /faculty-and-staff.

I created a test /faculty-and-staff view on History and the Faculty and Staff menu link immediately showed in the menu. :) :) :) :)

**Comment by mmafe** [comment]
Since this is an issue that is related more to the site setup than the migration module, I'm going to close it. If you find any further issues related to this, we can re-open.
