### ISSUE TITLE
CC - Allow Site Managers to add custom panes to a specific node layout (Configure Panelizer/Page Manager)

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#376]
Allow site managers to add custom panes to a specific node layout.

@brharp has recommended using Panelizer as a solution. https://www.drupal.org/project/panelizer

May require configuring page manager to allow use of panelizer.

Clients who are interested in this:
- Math & Stats
- Business
- SOCS

**Comment by chyatt** [comment]
@brharp dumb question - is this how we will accomplish landing pages?

**Comment by mmafe** [comment]
Clients would also like to add specific content to nodes of a specific taxonomy.

**Comment by mmafe** [comment]
@chyatt Brent says "Not necessarily, you can use Page Manager to create individual landing pages"

**Comment by brharp** [comment]
Also considering the nuclear option: provide page/block displays of all content panes, and use block manager for layout rather than panels. This would require:

- providing page/block versions of all content panes
- revisiting production sites and configuring block placement
- removing content panes
- disabling panel layouts

This would mean layouts could no longer be managed through features, but since nobody seems to like the default layouts anyway perhaps that's no great loss.

Default block placement can be provided in the install script, which clients may customize to their liking.
