### ISSUE TITLE
PP1 - Make People Profiles layout consistent with News/Events/Page listings (shift left if no image)

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#471]
Theming needs to be completed on People Profiles. Make listing page layout consistent with News/Events/Page listing pages. On both listing and detail pages, if no image is present, the content should shift left.
# Example of People Profiles

**Listing Page**
![image](https://cloud.githubusercontent.com/assets/1927902/15787034/dc3f6b48-298d-11e6-8aa1-6a63059037f0.png)

**Detail Page**
![image](https://cloud.githubusercontent.com/assets/1927902/15787076/33f91898-298e-11e6-8eac-684c16af9aa8.png)
# Example of News (Preferred)

**Listing Page**
![image](https://cloud.githubusercontent.com/assets/1927902/15787021/c337e986-298d-11e6-9dc7-2837353a619c.png)

**Comment by brharp** [comment]
Joy and Brent tried to replicate the news layout for profiles, but since profiles use Display Suite, we would have had to re-design the view to use fields.

Brent tried supplying a default image if none is provided when the node is saved, this works but does not generate the different image styles (small, large, etc.) automatically. If someone can figure out a way to have the image styles generated automatically, this way should work. See branch issue471.

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PP2 - Make People Profiles layout consistent with News/Events/Page listings (shift left if no image)](https://trello.com/c/tIoVEvOP/225-pp2-make-people-profiles-layout-consistent-with-news-events-page-listings-shift-left-if-no-image)

**Comment by ushenoyuog** [comment]
This issue will be compltede as part of #625 Closing this issue.
