### ISSUE TITLE
People Profiles Listing - Client request to be able to search/sort people profiles by first and last name

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#586]
COA is wondering if there is a method by which they can:
- search for people by first and last name
- allow users to sort the listing by first and last name

Priority and feasibility of request still to be determined. Possible solutions could include an A-Z index, input search, etc.

**Comment by ushenoyuog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [People Profiles Listing - Client request to be able to search/sort people profiles by first and last name](https://trello.com/c/ENUFt9kd/2075-people-profiles-listing-client-request-to-be-able-to-search-sort-people-profiles-by-first-and-last-name)

**Comment by ushenoyuog** [comment]
As per the Profiles enhancements meeting we had on 23 Jan 2017 : it was decided that sort will not be implemented, as it is not a feature that might be used by a lot of users. 

Last name search will be implemented and tracked via the alreday existing github issue https://github.com/ccswbs/hjckrrh/issues/594

This issue is being marked as duplicate and closed.
