### ISSUE TITLE
Research websites (e.g. other institutions) and/or themes that provide a similar UX/UI to the presented rebranded vision

### ISSUE THREAD

**Issue by mmafe** [ccswbs/hjckrrh#685]
Research websites (e.g. other institutions) that provide a similar UX/UI to the presented rebranded vision

[Keeping track of Site Research + Functionality](https://uoguelphca-my.sharepoint.com/personal/mmafe_uoguelph_ca/_layouts/15/guestaccess.aspx?guestaccesstoken=DFM2yx9YUrkOGHyrVbCAU6ocIkYbXgZ4h8K8X66RbQY%3d&docid=2_04ed2e475371f41ecada14efbe1786820&rev=1)

**Comment by mmafe** [comment]
- https://www.guelphhumber.ca/
- https://www.jhu.edu/
- https://www.ubc.ca/

**Comment by ushenoyuog** [comment]
# Some More sites 

## Sites that use grids

- [Bucknell University](http://bucknell.edu/) Grid images with text overlay and links
- [Univ of Nebraska ](http://www.unl.edu/)
- [Oberlin](https://home.oberlin.edu/) Grids with onhover

**Comment by nevantan** [comment]
## Johns Hopkins
Just expanding on the site.
Link: https://www.jhu.edu

The video background provides a fairly eye-catching feature while still making the important aspects easily accessible (Apply, Visit, etc.) as a handful of links on the right-hand side. It is actually fairly accessible:
- Fully keyboard accessible
- "Skip to main content" link hidden at the top
- The video has a text alternative in the lower left, referenced by an "aria-describedby" attribute
- The video plays through once and stops when it's done
- The mobile site uses a still image instead of a video
- They use Javascript to keep text alternatives in sync with the video, but fall back on a still image when Javascript is disabled

There is some good information on video backgrounds in this article: http://thenewcode.com/777/Create-Fullscreen-HTML5-Page-Background-Video

**Comment by mmafe** [comment]
@ushenoyuog @nevantan These examples are fantastic! Since we have a good starting list of sites to look into technically, I'm going to move this issue to the Done pile for the sprint. We can still add ideas as we think of them here.

**Comment by mmafe** [comment]
**Other things to think about**
- which of these sites use Drupal
- how would we accomplish sidebar menu
- is it available in both Drupal and Wordpress?
- how would we handle the pause/play for the background video?
- what happens at the end of the video - does it repeat?
- look at some main UG areas (eg. Admissions) - how would we handle?

**Comment by mmafe** [comment]
From @chyatt: https://www.trentu.ca/ is another good example for you to refer to

**Comment by bdavey07** [comment]
http://hcaconsulting.ca/
