### ISSUE TITLE
Find out why the order of profiles in PP6 isn't being properly distributed to all sites

### ISSUE THREAD

**Issue by nevantan** [ccswbs/hjckrrh#749]
@ushenoyuog commented on [Fri May 19 2017](https://github.com/ccswbs/aoda-tasks/issues/85)

Find out why the order of profiles in PP6 isn't being properly distributed to all sites. Write test.

**Comment by bdavey07** [comment]
This issue was fixed in https://github.com/ccswbs/hjckrrh/pull/664, merged and released as part of [Release 15](https://github.com/ccswbs/hjckrrh/releases/tag/7.x-15.0), including commits d84a10c and a6400fc.  Installing a new site from master right now, the sort order is by last name ascending (desired way).  I checked the following sites and they are all set to sort by last name ascending.
- MathStat
- Business
- Engineering
- Arts
- ADA-CBS
- CBS
- CCS
- HR
- Computing
- Arboretum

Still need to write a test.
