### ISSUE TITLE
Profiles - Categories should be Multi Select

### ISSUE THREAD

**Issue by ushenoyuog** [ccswbs/hjckrrh#783]

**Comment by mmafe** [comment]
Good news! Looks like no profile view panes show the category field, so we don't have to worry about how the category is displayed. Since there are no changes the view panes, I'm assuming we don't have to make a test to check that the view panes are displaying properly.

In that case, this is a really quick change.

**Comment by mmafe** [comment]
**Update:** Going to write a test for this after all where we:
- create a profile with multiple categories
- check that the profile with multiple profiles shows up on a people listing page filtered by each category
