### ISSUE TITLE
Logo for brand Refresh 

### ISSUE THREAD

**Issue by ushenoyuog** [ccswbs/hjckrrh#788]
Sites to include in documentation

- [x] http://www.ridgetownc.uoguelph.ca
- [x] http://www.opened.uoguelph.ca
- [x] http://www.uoguelph.ca/csahs/
- [x] http://ovc.uoguelph.ca/
- [x] https://www.uoguelph.ca/registrar/
- [x] http://www.uoguelph.ca/50/
- [x] http://www.alumni.uoguelph.ca
- [x] http://www.uoguelph.ca/news/
- [x] https://courselink.uoguelph.ca

**Priority 1:** Logo with tagline on right
**Priority 2:** Logo with no tagline
Don't bother with tagline below (except for OpenEd and OVC which have already been done)

**Comment by nevantan** [comment]
# OVC
URL: http://ovc.uoguelph.ca/
Original:
![original](https://user-images.githubusercontent.com/25013998/28463676-a61bcece-6def-11e7-83d1-df4ccdd73e2b.png)

The logo on OVC is a CSS background image of an `<a>` tag. Swapping it out involves modifying the `background-image` style to use the new image file and applying the following styles:
```
width:100px;
height:100px;
background-size:100%;
```
This results in a correctly positioned logo:
![ovc-first-attempt](https://user-images.githubusercontent.com/25013998/28464169-fb0b7450-6df1-11e7-8995-29d86c70c08a.png)

The header background is a little messy (they used semi-transparent lines on the red/yellow/blue background image to outline the logo), so I cleaned up the image and added it to the CSS rule for the banner background:
![ovc-banner-background](https://user-images.githubusercontent.com/25013998/28464214-29e0fe26-6df2-11e7-89f0-e81abd6d78f8.png)
And the resulting page looks like this:
![fixed-background-image](https://user-images.githubusercontent.com/25013998/28464223-3a25369e-6df2-11e7-92fa-ddfa4f3f2000.png)

**Note:** The OVC site has some Javascript that swaps out the background image for some reason (I couldn't figure out why), and causes the old banner background to replace the new one I put in place.

OVC has no room for the tagline to the right of the logo due to the site title, but there is plenty of room below the logo. I changed the image file to this (one I modified myself, taking the text from the logo image sent to me by @ushenoyuog. Note the tagline text is below the logo and is white, so may not be visible on Github's white background):
![logo-with-tagline](https://user-images.githubusercontent.com/25013998/28464263-5f35e384-6df2-11e7-8659-125de0f26b59.png)

Which looks like this once in place:
![ovc-with-tagline](https://user-images.githubusercontent.com/25013998/28464287-795111ee-6df2-11e7-92da-75bd1dcbc455.png)
The tagline requires changing the following CSS on the logo:
```
height:150px;
```

**Comment by nevantan** [comment]
# Ridgetown Campus
URL: http://www.ridgetownc.uoguelph.ca/
Original:
![original](https://user-images.githubusercontent.com/25013998/28466072-2176a144-6df9-11e7-8745-d6b0c7c5a6cd.png)

Clearing out the old logo is done in two parts, firstly removing the yellow section which is part of the local nav bar, and second is replacing the black part of the logo with the new one. Once the new logo URL is set in the CSS, a few rules need to be modified:
```
width:190px;
background-size:auto 100%;
background-repeat:no-repeat;
```
Which will result in this:
![first-attempt](https://user-images.githubusercontent.com/25013998/28465960-a9107c98-6df8-11e7-84aa-ba977b7b6283.png)

I recommend moving the tagline up a bit to make it equidistant from the logo to the left and the navbar below:
![spaced](https://user-images.githubusercontent.com/25013998/28466106-3ea52fce-6df9-11e7-8d05-434f2e7b8fcc.png)

**Comment by nevantan** [comment]
# Open Ed
URL: http://opened.uoguelph.ca/
Original:
![original](https://user-images.githubusercontent.com/25013998/28468387-d574680a-6e00-11e7-94f9-a11f6f0ad8d3.png)

Open Ed uses a flexbox header, which makes it very easy to adjust. The logo could take up the full height by allocating a little more horizontal space:
```
flex:0 0 200px;
```
![option1](https://user-images.githubusercontent.com/25013998/28467060-97dc8c4c-6dfc-11e7-9f59-48cfcde8abfb.png)

However, including the tagline is a little more difficult. There isn't really space for a horizontal layout, vertical like OVC would work better. In this case, the changes mentioned before may be reverted as the vertical logo has the same dimensions as the current logo.

There is also the challenge of the tagline text on changing backgrounds. A transparent background like the nav links was attempted, but it didn't work well. The next attempt was to use white text with a dark drop shadow, like the Open Ed site title, and this looks better:
![shadow-pic1](https://user-images.githubusercontent.com/25013998/28468334-aee69488-6e00-11e7-86b9-7c8928f7c673.png)
![shadow-pic2](https://user-images.githubusercontent.com/25013998/28468338-aeec9518-6e00-11e7-94f3-0a9d725192a3.png)
![shadow-pic3](https://user-images.githubusercontent.com/25013998/28468337-aeeb47e4-6e00-11e7-89c6-a988f7e69fa7.png)
![shadow-pic4](https://user-images.githubusercontent.com/25013998/28468336-aee9effc-6e00-11e7-8922-cef59c62cd69.png)
![shadow-pic5](https://user-images.githubusercontent.com/25013998/28468335-aee80c3c-6e00-11e7-8a84-83a66cbe4ffb.png)

**Comment by nevantan** [comment]
# Social and Applied Human Sciences
URL: http://www.uoguelph.ca/csahs/
Original:
![original](https://user-images.githubusercontent.com/25013998/28469516-7bf44706-6e04-11e7-9e4f-1ef26f28a7ea.png)

Lots of space on this page for logo plus tagline. The tagline in the screenshot was moved up (original image has the tagline aligned to the bottom of the logo) and given a drop shadow to make it more visible on the red:
![full-height-white-space-shadow](https://user-images.githubusercontent.com/25013998/28469569-a33d687e-6e04-11e7-9ea0-966d54bd21af.png)

**Comment by nevantan** [comment]
# Registrar
URL:
Original:
![original](https://user-images.githubusercontent.com/25013998/28470071-8181babc-6e06-11e7-9a45-db181cf025a7.png)

The header is a little cramped, but the tagline can slide in right under the site title. Changes:
- The logo needs to be absolutely positioned and size adjusted
- The yellow part of the old logo removed as the background image
- The site title needs a larger `left` attribute to make room for the wider logo

Result:
![side](https://user-images.githubusercontent.com/25013998/28469969-1ba52a76-6e06-11e7-8dc4-919f5cb34841.png)

Alternatively, the logo could remain small and the tagline moved up a little, it would work similarly:
![small](https://user-images.githubusercontent.com/25013998/28470091-9432031a-6e06-11e7-81df-3f675ce71ba3.png)

**Comment by morganrees9** [comment]
# Courselink

**URL:** https://courselink.uoguelph.ca/

## Original

![courselink-original](https://user-images.githubusercontent.com/25161107/28471202-560f5f7a-6e0a-11e7-8f78-988e1bcc767b.png)

## Logo with Tagline on Right

![courselink-tagline-right](https://user-images.githubusercontent.com/25161107/28471210-5fa823fa-6e0a-11e7-9268-464738f22fad.png)

## Logo with No Tagline

![courselink-tagline-none](https://user-images.githubusercontent.com/25161107/28471222-69e9ec40-6e0a-11e7-9a2b-8c079a6e36f7.png)

**Comment by nevantan** [comment]
# UoG 50
URL: http://www.uoguelph.ca/50/
Original:
![original](https://user-images.githubusercontent.com/25013998/28475171-3f0fe772-6e19-11e7-8a0d-8149f58ec644.png)

Despite what it looks like, the "logo" in the upper left is actually a single image, not just the special 50-year banner next to the regular image. The split occurs along the yellow line, it seems the same image (50-year plus regular logo) is used twice, once in the red section and once again in the navbar area. The solution was to cut a chunk out of the lower left so we're just left with the black square plus 50-year logo:
![universityofguelph50](https://user-images.githubusercontent.com/25013998/28475270-9409c8ba-6e19-11e7-93d9-80e671ecdd00.png)

Which results in this:
![no-old-tagline](https://user-images.githubusercontent.com/25013998/28475281-98a0e5ac-6e19-11e7-94e0-84becf252c47.png)

**Comment by morganrees9** [comment]
# News

## Small Logo, No tagline

![news-tagline-none-small-image](https://user-images.githubusercontent.com/25161107/28475455-3c9208bc-6e1a-11e7-8ab5-145532679b4a.png)

## Large Logo, No Tagline

![news-tagline-none-large-image](https://user-images.githubusercontent.com/25161107/28475467-48bbef9a-6e1a-11e7-841c-21bfab353d6e.png)

## Large Logo, with Tagline

![news-tagline-right](https://user-images.githubusercontent.com/25161107/28475475-5ccff774-6e1a-11e7-94df-795fb72c2db2.png)

**Comment by nevantan** [comment]
# Alumni
URL:
Original:
![without-tagline](https://user-images.githubusercontent.com/25013998/28475538-acc26b54-6e1a-11e7-96bc-4d3988205e3f.png)

This site already looks like it conforms to the new brand guidelines (even if unintentionally). Experimented with the tagline anyway:
![with-tagline](https://user-images.githubusercontent.com/25013998/28475554-c8818bae-6e1a-11e7-96c2-f5db70509494.png)

It could fit below the site title, but may require reworking some markup to do so.

**Comment by nevantan** [comment]
The D7 theme has notes in ccswbs/pequod#45.

**Comment by nevantan** [comment]
**Additional Note:** The tagline doesn't work well due to the requirement that the tagline be aligned with the lower edge of the logo. See the attached screenshots for reference.

![hjckrrh-new-logo-big](https://user-images.githubusercontent.com/25013998/28588322-31a7aca0-7148-11e7-885a-b20a2f78a97d.png)
![hjckrrh-new-logo-small](https://user-images.githubusercontent.com/25013998/28588323-329f41b8-7148-11e7-98c8-8df492ee0aa5.png)
