### ISSUE TITLE
Testing Strategy Research

### ISSUE THREAD

**Issue by nevantan** [ccswbs/hjckrrh#815]
**Notes:**
- _Everything_ should be covered by tests, either ours or Drupal's
- Tests should be run in isolation and anything outside of what is being tested should be avoided. A notable example of this is that, unless the UI itself is being tested, we should be accessing functions directly rather than controlling them from the UI
- Tests should not be repeated. If components A and B have already been unit tested, an E2E test does not need to test the components themselves; rather, it should test specifically how they interact with each other
- 

**References:**
- https://www.mountaingoatsoftware.com/blog/the-forgotten-layer-of-the-test-automation-pyramid
- https://www.thoughtworks.com/insights/blog/functional-tests-how-decide-what-automate
- http://blog.dcycle.com/blog/52/eight-tips-remember-your-path-automated-testing/
- https://www.digett.com/insights/testing-checklist-drupal-website
- https://hackernoon.com/testing-your-frontend-code-part-i-introduction-7e307eac4446
- https://hackernoon.com/testing-your-frontend-code-part-ii-unit-testing-1d05f8d50859

**Comment by mmafe** [comment]
# Continuous Integration Testing Strategy Notes

## The Ideal
- tests written before developers start work on the features that they test
- tests are run every time a change is made to the application

### Automated Acceptance Tests
- good rule of thumb: automate once you have repeated the same test a couple of times
- not everything needs to be automated (e.g. usability, consistency of look and feel). Some aspects people are better at testing

**Comment by mmafe** [comment]
# What should we be testing in Drupal
Results of brainstorming with @ushenoyuog 

- Is it dependent on an existing component? Yes? ---> write a test to ensure the behaviour will not break because the existing component no longer exists (e.g. if people/tag/<termID> stopped working because we removed PP5, we'd want to ensure that any view panes that link to people/tag/<termID> fail a test so we can know to fix those other view panes).
- Is it a main happy path? Yes? --> write a test
