### ISSUE TITLE
E1 - Summary never shows up / Listing shows multiple h2 headings if body text includes headings

### ISSUE THREAD

**Issue by jszasz** [ccswbs/hjckrrh#87]
The "Body" text will show up on the view, but if there is a summary it doesn't appear. The view will display a snipped version of the body regardless of if there is a summary or not.

If there is a summary the view should show that, if there isn't, should use the body.

**Comment by jszasz** [comment]
Still an issue. Listing pages show a snippet of the "body" and never use the "summary".

**Comment by mmafe** [comment]
Noticed this occurring on a production site. It causes an accessibility issue if we have an H2 title followed by a summary with an H2 heading. Suggest we use the summary field instead of the body field on this view.

![image](https://cloud.githubusercontent.com/assets/1927902/13828917/884f883c-eb9a-11e5-9cc0-2f86210145a0.png)

**Comment by abanuog** [comment]
closing as it looks like it has been resolved.
